Repository artefactory/choice-learn, pull requests merged in 2025-02, with the labels that each got.

#220 Few changes
  README.md
  choice_learn/basket_models/shopper.py
  choice_learn/basket_models/trip_dataset.py
  notebooks/basket_models/shopper_tutorial.ipynb
  tests/integration_tests/basket_models/test_utilities_and_likelihoods.py
  tests/unit_tests/basket_models/test_dataset.py
Labels: enhancement

#216 Basket models
  README.md
  choice_learn/basket_models/__init__.py
  choice_learn/basket_models/dataset.py
  choice_learn/basket_models/preprocessing.py
  choice_learn/basket_models/shopper.py
  choice_learn/basket_models/utils/permutation.py
  choice_learn/data/storage.py
  choice_learn/datasets/base.py
  choice_learn/models/base_model.py
  choice_learn/tf_ops.py
  docs/index.md
  docs/references/basket_models/references_shopper.md
  docs/references/basket_models/references_trip_dataset.md
  docs/references/basket_models/references_trip_preprocessing.md
  docs/references/basket_models/utils/references_permutation.md
  notebooks/basket_models/basket_data.ipynb
  notebooks/basket_models/shopper.ipynb
  notebooks/basket_models/synthetic_dataset.py
  tests/integration_tests/basket_models/test_shopper_on_tripdataset.py
  tests/unit_tests/basket_models/test_dataset.py
  tests/unit_tests/basket_models/test_permutation.py
  tests/unit_tests/basket_models/test_preprocessing.py
  tests/unit_tests/basket_models/test_shopper.py
Labels: new feature

#226 Fix documentation
  README.md
  docs/references/basket_models/references_dataset.md
  docs/references/basket_models/references_preprocessing.md
  docs/references/basket_models/references_trip_dataset.md
  docs/references/basket_models/references_trip_preprocessing.md
  mkdocs.yaml
Labels: documentation

#231 ENH: batch processing for Shopper.evaluate()
  choice_learn/basket_models/shopper.py
Labels: enhancement

#232 ENH: no trainable lambda for the checkout item in Shopper
  choice_learn/basket_models/shopper.py
  tests/integration_tests/basket_models/test_shopper_on_tripdataset.py
Labels: enhancement
